export const SAVE_MASTER_TYPE_INITIATED = "SAVE_MASTER_TYPE_INITIATED";
export const SAVE_MASTER_TYPE_SUCCESS = "SAVE_MASTER_TYPE_SUCCESS";
export const SAVE_MASTER_TYPE_ERROR = "SAVE_MASTER_TYPE_ERROR";

export const GET_MASTER_TYPE_LIST_INITIATED = "GET_MASTER_TYPE_LIST_INITIATED";
export const GET_MASTER_TYPE_LIST_SUCCESS = "GET_MASTER_TYPE_LIST_SUCCESS";
export const GET_MASTER_TYPE_LIST_ERROR = "GET_MASTER_TYPE_LIST_ERROR";

export const GET_MASTER_TYPE_BY_ID_INITIATED = "GET_MASTER_TYPE_BY_ID_INITIATED";
export const GET_MASTER_TYPE_BY_ID_SUCCESS = "GET_MASTER_TYPE_BY_ID_SUCCESS";
export const GET_MASTER_TYPE_BY_ID_ERROR = "GET_MASTER_TYPE_BY_ID_ERROR";

export const DELETE_MASTER_TYPE_BY_ID_INITIATED = "DELETE_MASTER_TYPE_BY_ID_INITIATED";
export const DELETE_MASTER_TYPE_BY_ID_SUCCESS = "DELETE_MASTER_TYPE_BY_ID_SUCCESS";
export const DELETE_MASTER_TYPE_BY_ID_ERROR = "DELETE_MASTER_TYPE_BY_ID_ERROR";

export const SAVE_MASTER_INITIATED = "SAVE_MASTER_INITIATED";
export const SAVE_MASTER_SUCCESS = "SAVE_MASTER_SUCCESS";
export const SAVE_MASTER_ERROR = "SAVE_MASTER_ERROR";

export const GET_MASTER_LIST_INITIATED = "GET_MASTER_LIST_INITIATED";
export const GET_MASTER_LIST_SUCCESS = "GET_MASTER_LIST_SUCCESS";
export const GET_MASTER_LIST_ERROR = "GET_MASTER_LIST_ERROR";

export const GET_MASTER_BY_ID_INITIATED = "GET_MASTER_BY_ID_INITIATED";
export const GET_MASTER_BY_ID_SUCCESS = "GET_MASTER_BY_ID_SUCCESS";
export const GET_MASTER_BY_ID_ERROR = "GET_MASTER_BY_ID_ERROR";

export const DELETE_MASTER_BY_ID_INITIATED = "DELETE_MASTER_BY_ID_INITIATED";
export const DELETE_MASTER_BY_ID_SUCCESS = "DELETE_MASTER_BY_ID_SUCCESS";
export const DELETE_MASTER_BY_ID_ERROR = "DELETE_MASTER_BY_ID_ERROR";

export const SAVE_KRA_INITIATED = "SAVE_KRA_INITIATED";
export const SAVE_KRA_SUCCESS = "SAVE_KRA_SUCCESS";
export const SAVE_KRA_ERROR = "SAVE_KRA_ERROR";

export const GET_KRA_LIST_INITIATED = "GET_KRA_LIST_INITIATED";
export const GET_KRA_LIST_SUCCESS = "GET_KRA_LIST_SUCCESS";
export const GET_KRA_LIST_ERROR = "GET_KRA_LIST_ERROR";

export const GET_KRA_BY_ID_INITIATED = "GET_KRA_BY_ID_INITIATED";
export const GET_KRA_BY_ID_SUCCESS = "GET_KRA_BY_ID_SUCCESS";
export const GET_KRA_BY_ID_ERROR = "GET_KRA_BY_ID_ERROR";

export const DELETE_KRA_BY_ID_INITIATED = "DELETE_KRA_BY_ID_INITIATED";
export const DELETE_KRA_BY_ID_SUCCESS = "DELETE_KRA_BY_ID_SUCCESS";
export const DELETE_KRA_BY_ID_ERROR = "DELETE_KRA_BY_ID_ERROR";

export const SAVE_KPI_INITIATED = "SAVE_KPI_INITIATED";
export const SAVE_KPI_SUCCESS = "SAVE_KPI_SUCCESS";
export const SAVE_KPI_ERROR = "SAVE_KPI_ERROR";

export const UPLOAD_DOC_INITIATED = "UPLOAD_DOC_INITIATED";
export const UPLOAD_DOC_SUCCESS = "UPLOAD_DOC_SUCCESS";
export const UPLOAD_DOC_ERROR = "UPLOAD_DOC_ERROR";